language: julia
os:
  - linux
  - osx
sudo: required
julia:
  - 1.0
  - 1.1
  - 1.2
  - 1.3
  - nightly
notifications:
  email: false
# after_success:
#   - julia -e 'cd(Pkg.dir("LibArchive")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
